More docs
Sensor-Based-Activity-Recognition/docs pull request #24
Opened 2023-06-05 12:11 UTC by gabrieltorresgamez

References

https://github.com/Sensor-Based-Activity-Recognition/docs/issues/23

2023-06-05 12:13 UTC, gabrieltorresgamez commented
Ich bi nöd all zu zfriede mit minere ergänzig abr bin grad bitz hilflos. Was sötti no id Zämmefassig hinzuefüege? sötti die Sache irgedwie/irgedwo anders dokumentiere?

2023-06-05 21:17 UTC, florinbarbisch requested changes

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Der Train-Val-Test-Split wurde entweder auf segmentebasierter Ebene oder durch einen personenbasierten Split durchgeführt, um die Leistung des Systems zu bewerten. Bei einem segmentbasierten Split wu
> um eine detaillierte Bewertung der Aktivitätserkennung zu ermöglichen

Isch doch bi beidne ahsätz dr fall?

> Diese Methode berücksichtigt individuelle Unterschiede zwischen den Benutzern und ermöglicht eine genauere Bewertung der Systemleistung für jede einzelne Person.

Chumi nid drus.



Für mi isch das nid verständlich de abschnitt. Chasch de ganz absatz umschriebe:
Zersch erkläre, dass mir zwöi ahsätz fürs splitting hei. Denne seisch das de person-based für en app besser wär wo au benutzer installiere wo kei date contributed hei (smartphone/-watch hersteller) und me brucht vill date derzue. Das hei mir aber nid und üses ziel isch au nid en app für anderi persone z mache sondern en app für üs und drum hei mir en segment based gmacht.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Zur Bewertung der Modellleistung wurden die Accuracy und der Macro F1-Score verwendet. Die Accuracy gibt an, wie gut das Modell insgesamt die Aktivitäten klassifiziert, während der Macro F1-Score ein
> Zur Bewertung der Modellleistung wurden die Accuracy und der Macro F1-Score verwendet

Gemäss Konzept judge mir nach F1 und mir düe eifach au no d accuracy reporte.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +In diesem Projekt haben wir uns für einen segmentbasierten Split entschieden, da wir aufgrund der begrenzten Datenmenge von nur 10 Personen nicht genügend Daten hatten, um ein Modell zu entwickeln, d
Setz dr fokus vor begründig ufs argument, dass mir en app entwickle wo nur üsi activities classified. s andere darfsch scho erwähne, aber bitte ersch an 2ter stell.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Ein ausführliche Übersicht aller Modelle kann man unter [Modelle](https://github.com/Sensor-Based-Activity-Recognition/docs/blob/main/Modelle.md) finden.
Würde ich wie folgt anpassen:

Ein ausführliche Übersicht aller Modelle ~kann man~ **ist** unter [...] **zu** finden.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Die Daten wurden aus der Datenbank extrahiert und auf 50Hz resampelt. Anschliessend wurden sie in 5-Sekunden-Fenster aufgeteilt. Während der STFT-Phase wurden die Spectrogram,e erstellt. Die Phase dv
> Spectrogram,e

sollte wohl _Spectrograme,_ heissen

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Die Architektur des Modells besteht aus vier Convolutional Layers, gefolgt von Pooling Layers. Nach dem Convolution-Teil folgt eine Global Average Pooling Layer und zwei Fully Connected Layers. Das M
>, gefolgt von Pooling Layers

müsste heissen: 

, **jeweils** gefolgt von Pooling Layers

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Das HGBC-Modell verwendet den [HistGradientBoostingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html) von sklearn. Als Eingabe für uns
> Anschliessend wurde ein Train-Test-Split durchgeführt und das Modell wurde trainiert.

Würde ich beim CNN auch noch erwähnen. Sonst hat man das Gefühl, dass dies nur beim HGBC-Modell getan wird.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Der Vergleich der beiden Modelle ergab, dass sowohl das CNN-Modell als auch das HGBC-Modell beeindruckende Ergebnisse erzielten. Das CNN-Modell zeigte seine Stärken bei der Erkennung von Aktivitäten
Viiel zu kurz. Und nid würklich ussagechräftiger als ChatGPT.

Würd uf d fehler us dr konfusionsmatrix goh, und argumentiere, dass dank üsem guete preprocessing s HGBC besser isch. Do chasch au no allgmein druf ihgoh, wieso deep learning nid besser isch, respektive wies sich im ahsatz mit klassischem ML unterscheidet (eifach mal alli date ine schmeisse (deep learning) vs Features manuell extrahiere (ML)).

Vllt chasch do no chli reserach betriibe wenn klassisches ML superior zu deep learning isch und luege, was au ahwendig uf üses projekt het.

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
> +Eine wichtige Lesson Learned ist, dass man nicht ausschliesslich auf Deep Learning Modelle setzen sollte. Es ist auch wichtig, herkömmliche Machine Learning Modelle zu analysieren und in Betracht zu
Hei mir do nid no meh sache gha?

Paar vorschläg vo mir
- [ ] nutze vo DVC (vllt no das mir mit stages baue übertriebe hei bevor mir es modell hei gha und jetzt vill unbruchti stages hei)
- [ ] segment- vs people-based split (split ist nicht immer einfach pro datenpunkt)
- [ ] why gradient boosting (said to be superior in many kaggle challenges)
- [ ] schwierigkeiten mit daten von unterschiedlichen sensore: **BENNNNN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

2023-06-05 21:17 UTC, florinbarbisch commented on Zusammenfassung.md
Wenn wosch chasch no was übers team/Projectmanagement schriebe (flexe mit tools, dass alles guet abgloffe isch und mir eifach die beste si)

2023-06-05 21:18 UTC, florinbarbisch commented on Modelle.md
> +CML Report: https://github.com/Sensor-Based-Activity-Recognition/pipelines/pull/98#issuecomment-1564147778
Markdown kennt [Links](https://github.com/Sensor-Based-Activity-Recognition/pipelines/pull/98#issuecomment-1564147778)!!!

2023-06-05 21:18 UTC, florinbarbisch commented on Modelle.md
> +CML Report: https://github.com/Sensor-Based-Activity-Recognition/pipelines/pull/99#issuecomment-1564102269
Markdown kennt [Links](https://github.com/Sensor-Based-Activity-Recognition/pipelines/pull/99#issuecomment-1564102269)!!!

2023-06-08 09:17 UTC, gabrieltorresgamez commented on Modelle.md
> +CML Report: https://github.com/Sensor-Based-Activity-Recognition/pipelines/pull/98#issuecomment-1564147778
ich bi aber rechts

2023-06-08 09:18 UTC, gabrieltorresgamez commented
@florinbarbisch made some changes, whats your impression now?

2023-06-08 14:06 UTC, florinbarbisch requested changes

2023-06-08 14:06 UTC, florinbarbisch commented on Zusammenfassung.md
> +- Wir haben den Macro F1-Score genommen, um festzustellen, ob ein Modell eine bestimmte Klasse bevorzugt. Wenn der F1-Score der Accuracy nahe liegt, deutet das darauf hin, dass unser Modell keine Kla
> ob ein Modell eine bestimmte Klasse bevorzugt

lässt sich nicht ableiten. (Auch ist der F1 ein einziger Fakt).

2023-06-08 14:06 UTC, florinbarbisch commented on Zusammenfassung.md
> +- Wir haben den Macro F1-Score genommen, um festzustellen, ob ein Modell eine bestimmte Klasse bevorzugt. Wenn der F1-Score der Accuracy nahe liegt, deutet das darauf hin, dass unser Modell keine Kla
ok sehe was du sagen willst: "ob ein Modell alle Klasse gleich gut klassifizieren kann".

2023-06-08 14:06 UTC, florinbarbisch commented on Zusammenfassung.md
> +- Zusätzlich generieren wir aus Debugging-Gründen auch eine Decision Matrix.
Würde sagen: falls F1 und accuracy nicht wie oben erwähnt nahe bei einander liegen: können wir die fehler in der Decision-Matrix untersuchen. 

Das Wort Debugging bezieht sich eher auf technische vorgänge und nicht aus menschlichen.

2023-06-08 14:06 UTC, florinbarbisch commented on Zusammenfassung.md
> +Die Architektur des Modells besteht aus vier Convolutional Layers, gefolgt von Pooling Layers. Nach dem Convolution-Teil folgt eine Global Average Pooling Layer und zwei Fully Connected Layers. Das M
Bitte anpassen @gabrieltorresgamez

2023-06-09 10:41 UTC, gabrieltorresgamez commented on Zusammenfassung.md
> +- Zusätzlich generieren wir aus Debugging-Gründen auch eine Decision Matrix.
vorallem ist niemandem von uns aufgefallen, dass es eine confusion matrix und nicht eine decision matrix ist hahahah

2023-06-09 12:45 UTC, gabrieltorresgamez commented
@buesst1 nice commit name

![image](https://github.com/Sensor-Based-Activity-Recognition/docs/assets/60326390/c8807aab-f345-4fa1-ab80-2a9f1bb6c6af)

2023-06-10 08:00 UTC, florinbarbisch approved these changes

2023-06-10 08:01 UTC, merged